Repository MouseGamza/Todays-Chef, pull requests merged in 2021-12, with the labels that each got.

#182 [Client] / #59 / mypage 예약 확인 페이지 구현
  client/src/component/mypageReservation.js
  client/src/features/reservation/reservation.js
  client/src/modal/deleteReservModal.js
Labels: Basic, C:5h

#184 [Server] / #60 / mypage user reservation corse 이름 추가
  server/controllers/mypage/checkReservation.js
Labels: Back-end, Complete, Basic, C:0.5h

#185 [Client] / #60 / pagenation 수정
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/adminpageReview.js
  client/src/component/chefInfoReview.js
  client/src/component/login.js
  client/src/component/mypageReservation.js
  client/src/features/user/modal.js
  client/src/modal/adminOrChefWarningModal.js
  client/src/pages/findChef.js
  client/src/pages/reservation.js
  server/controllers/admin/bechef.js
  server/controllers/admin/chef.js
  server/controllers/admin/review.js
  server/controllers/chef/chefId.js
  server/controllers/chef/cuisine.js
Labels: Front-end, Back-end, Basic, C:2h

#186 [Server] / #61 / login 할 때 chefId 주기
  server/controllers/user/login.js
Labels: Back-end, Basic, C:0.5h

#187 [Server] / #62 / mainpage에서 보여질 cuisine별 best chef 구현 완료
  server/app.js
  server/controllers/index.js
  server/controllers/mainpage/bestChef.js
  server/controllers/mainpage/index.js
  server/routes/mainPage.js
Labels: Back-end, Complete, Basic, C:1h

#188 [Client] / #61 / rating 별 img 첨부
  client/src/pages/findChef.js
  client/src/styled/styleFindChef.js
  client/src/todaysChefIMG/halfStar.svg
  client/src/todaysChefIMG/noneStar.svg
  client/src/todaysChefIMG/ratingStar.svg
Labels: Front-end, Basic, C:0.5h

#189 [Client] / #62 / mypage review axios 작업중
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/features/chef/chef.js
  client/src/features/review/review.js
Labels: Front-end, C:2h

#190 [Client] / #63 / mypage axios, redux 작업중
  client/src/component/chefInfoReview.js
  client/src/component/login.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/features/chef/chef.js
  client/src/features/review/review.js
  client/src/features/user/modal.js
  client/src/modal/adminOrChefWarningModal.js
  client/src/modal/oneSentenceModal.js
  client/src/modal/oneSentenceSuccessModal.js
  client/src/pages/mypage.js
  client/src/pages/reservation.js
  client/src/styled/styleMypage.js
  server/controllers/mypage/checkReview.js
  server/controllers/mypage/chefInfo.js
  server/controllers/user/google.js
Labels: Front-end, Basic, C:5h

#194 [Server] / #63 / mypage chefInfo course 추가
  server/controllers/mypage/chefInfo.js
Labels: Back-end, Complete, Basic, C:0.5h

#195 [Server] / #64 / 소셜 로그인 했을 때 isChef Boolean 값으로 chefId 건내주기
  server/controllers/user/google.js
  server/controllers/user/kakao.js
Labels: Back-end, Complete, Basic, C:1h

#196 [Client] / #65 / chefImg 및 userImg 불러오기 작업, 별점 svg 변경
  client/src/component/chefInfoReview.js
  client/src/component/mainSection3.js
  client/src/pages/findChef.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMain.js
  client/src/todaysChefIMG/halfStar.svg
  client/src/todaysChefIMG/noneStar.svg
  client/src/todaysChefIMG/ratingStar.svg
Labels: Front-end, Complete, Basic, C:1h

#197 [Server] / #65 / rating 평균 내기 업데이트
  client/src/component/mainSection3.js
  client/src/pages/findChef.js
  server/controllers/mypage/checkReview.js
Labels: Back-end, Basic, C:2h

#198 [Server / Client] / #13 / mypage edit 작업
  client/package.json
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/component/reservationPayment.js
  client/src/component/signup.js
  client/src/features/chef/chef.js
  client/src/features/user/modal.js
  client/src/features/user/user.js
  client/src/modal/choiceModal.js
  client/src/modal/logoutModal.js
  client/src/modal/oneSentenceSuccessModal.js
  client/src/pages/mypage.js
  client/src/styled/styleMypage.js
  client/src/styled/styleReservation.js
  server/controllers/mypage/checkReview.js
  server/controllers/mypage/chefInfo.js
  server/controllers/mypage/image.js
Labels: Front-end, Back-end

#199 [Client] / #66 / iamport 클라이언트 코드 작성
  client/src/component/reservationPayment.js
  client/src/modal/addressModal.js
  client/src/pages/reservation.js
  client/src/styled/styleReservation.js
Labels: Front-end

#200 [Client / Server] reservation payment 기본 세팅 완료
  client/src/component/reservationPayment.js
  server/controllers/reservation/index.js
  server/controllers/reservation/payments.js
  server/routes/reservation.js
Labels: Front-end, Back-end, Basic

#201 [Client / Server] / #15 / 결제완료 서버에서 조회까지 구현
  client/public/index.html
  client/src/component/reservationPayment.js
  server/controllers/reservation/payments.js
  server/controllers/reservation/reservation.js
  server/controllers/user/google.js
  server/migrations/20211023054329-create-reservation.js
  server/models/reservation.js
  server/routes/reservation.js
  server/seeders/20211102060437-dummyReservations.js
Labels: Front-end, Back-end, Basic, C:5h

#202 [Client] / #67 / mypage 관련 redux, axios작업
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/component/reservationDone.js
  client/src/component/reservationPayment.js
  client/src/component/signup.js
  client/src/features/user/modal.js
  client/src/modal/choiceModal.js
  client/src/modal/deleteReservModal.js
  client/src/modal/oneSentenceModal.js
  client/src/styled/styleMypage.js
  client/src/styled/styleReservation.js
Labels: Front-end

#206 [Client / Server] / #17 / 결제시스템 구현 완료
  client/src/component/mypageReservation.js
  client/src/features/user/modal.js
  client/src/modal/deleteReservModal.js
  server/controllers/mypage/checkReservation.js
  server/controllers/reservation/payments.js
  server/migrations/20211023054329-create-reservation.js
  server/models/reservation.js
Labels: Front-end, Back-end, Complete, Basic, C:5h

#208 [Client] / #68 / mypage axios 수정 및 reservation 수정
  client/src/component/chefInfoReview.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageReservation.js
  client/src/component/reservationDate.js
  client/src/component/reservationPayment.js
  client/src/pages/reservation.js
  client/src/styled/styleMypage.js
Labels: Front-end

#210 [Server] aws accesskey 이름 바꾸기
  server/modules/multer.js
Labels: Back-end, Basic

#211 [Client] / #69 / 탈퇴 처리
  client/src/component/mypageEdit.js
Labels: Front-end

#212 [Client] 탈퇴처리
  client/src/component/mypageEdit.js
Labels: Front-end, Basic

#214 [Server] social login console.log
  server/controllers/user/kakao.js
Labels: Back-end, Basic

#215 [Server] social login console.log
  server/controllers/user/kakao.js
Labels: Back-end, Basic

#218 [Client] / #70 / footer 작업
  client/src/component/footer.js
  client/src/component/mypageReview.js
  client/src/modal/oneSentenceModal.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleFooter.js
  client/src/styled/styleLoginOrSignup.js
  client/src/styled/styleNav.js
Labels: Front-end

#219 [Server] / #66 / chefImage 작업, reservationDate 작업, 조건 rating 작업
  server/controllers/chef/chefId.js
  server/controllers/mypage/chefImg.js
  server/controllers/mypage/image.js
  server/controllers/mypage/index.js
  server/controllers/reservation/reservation.js
  server/controllers/user/login.js
  server/routes/mypage.js
Labels: Back-end, Complete, Basic, C:3h

#222 [Client / Server] nodemailer 관련 수정
  client/src/component/adminpageBechef.js
  server/controllers/admin/bechefIsConfirm.js
Labels: Front-end, Back-end

#224 [Client] reservation date-picker 관련 수정
  client/src/component/reservationDate.js
  client/src/pages/reservation.js
Labels: Front-end

#225 [Server] sendMail port 변경
  client/src/component/reservationPayment.js
  server/controllers/admin/bechefIsConfirm.js
  server/controllers/reservation/findCourse.js
  server/controllers/reservation/payments.js
  server/controllers/sendMail.js
Labels: Back-end, Basic

#227 [Server] reservation accessToken 및 refreshToken 추가
  server/controllers/reservation/reservation.js
Labels: Back-end, Basic

#228 [Client] css 변경 및 star component 관련 수정
  client/src/component/chefInfoReview.js
  client/src/component/login.js
  client/src/component/mainSection3.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/features/user/user.js
  client/src/modal/needReLoginModal.js
  client/src/modal/pictureModal.js
  client/src/pages/chefInfo.js
  client/src/pages/findChef.js
  client/src/pages/mypage.js
  client/src/pages/reservation.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMain.js
  server/controllers/mypage/checkReservation.js
  server/controllers/token/accessToken.js
Labels: Front-end, C:3h

#229 [Server] scripts start.sh
  scripts/start.sh
Labels: Back-end, Basic, C:0.5h

#233 [Client] / #71 / main bestOfChefsWrap Link 연결 작업
  client/src/component/mainSection3.js
  client/src/styled/styleMain.js
Labels: Front-end

#234 [Server] kakao headers error 수정
  scripts/start.sh
  server/controllers/token/refreshToken.js
  server/controllers/user/kakao.js
Labels: Back-end, Basic

#235 [Client] / #72 / css 수정 및 import 관련 m_redirect_url 지정
  client/src/App.js
  client/src/component/mypageEdit.js
  client/src/component/reservationDone.js
  client/src/component/reservationInfo.js
  client/src/component/reservationPayment.js
  client/src/modal/addressModal.js
  client/src/pages/beChef.js
  client/src/pages/reservation.js
  client/src/pages/reservationDonePage.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMain.js
  client/src/styled/styleReservation.js
  client/src/styled/styledModal.js
Labels: Front-end

#238 [Client] / #73 / url 수정
  client/src/component/reservationPayment.js
Labels: Front-end

#240 [Client] payment url 수정
  client/src/component/reservationPayment.js
Labels: Front-end, Basic

#241 [Client] / reservationDonePage axios 수정
  client/src/component/reservationPayment.js
  client/src/pages/reservationDonePage.js
Labels: Front-end

#242 [Client] reservationDonePage.js 수정
  client/src/pages/reservationDonePage.js
Labels: Front-end

#243 [Client] reservationDonePage axios 수정
  client/src/pages/reservationDonePage.js
Labels: Front-end

#245 [Client] new Date 관련 수정
  client/src/pages/reservationDonePage.js
Labels: Front-end

#246 [Client] date 관련 수정
  client/src/component/reservationPayment.js
  client/src/pages/reservationDonePage.js
Labels: Front-end

#247 [Client] date 수정
  client/src/pages/reservationDonePage.js
Labels: Front-end

#248 [Client] js date-fns 관련 수정
  client/src/pages/reservationDonePage.js
Labels: Front-end

#250 [Client] css 수정 및 console.log 찍어보기
  client/src/component/mainSection3.js
  client/src/component/mypageReview.js
  client/src/component/reservationPayment.js
  client/src/pages/findChef.js
  client/src/pages/reservationDonePage.js
  client/src/styled/styleMain.js
Labels: Front-end

#251 [Client] reservation date test 변경
  client/src/pages/reservationDonePage.js
Labels: Front-end, Basic

#252 [Client] / #74 / findChef 이동 관련 수정
  client/src/App.js
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/chefInfoReview.js
  client/src/component/login.js
  client/src/component/mainSection2.js
  client/src/component/mainSection3.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/component/reservationDate.js
  client/src/component/reservationDone.js
  client/src/component/reservationInfo.js
  client/src/component/reservationPayment.js
  client/src/features/chef/chef.js
  client/src/features/user/modal.js
  client/src/features/user/user.js
  client/src/modal/addressModal.js
  client/src/modal/logoutModal.js
  client/src/modal/needReLoginModal.js
  client/src/modal/pictureModal.js
  client/src/pages/beChef.js
  client/src/pages/chefInfo.js
  client/src/pages/findChef.js
  client/src/pages/mypage.js
  client/src/pages/reservation.js
  client/src/pages/reservationDonePage.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMain.js
  client/src/styled/styleMypage.js
  client/src/styled/styleReservation.js
  client/src/styled/styledModal.js
  scripts/start.sh
  server/controllers/admin/bechefIsConfirm.js
  server/controllers/chef/chefId.js
  server/controllers/mypage/checkReservation.js
  server/controllers/reservation/findCourse.js
  server/controllers/reservation/index.js
  server/controllers/reservation/payments.js
  server/controllers/reservation/reservation.js
  server/controllers/sendMail.js
  server/controllers/token/accessToken.js
  server/controllers/token/refreshToken.js
  server/controllers/user/google.js
  server/controllers/user/kakao.js
  server/modules/multer.js
Labels: Front-end

#255 [Client] / #76 / css 전제적 수정
  client/src/component/nav.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleMain.js
  client/src/styled/styleMypage.js
  client/src/styled/styleNav.js
Labels: Front-end, Basic

#253 [Client] / #75 / 사진 모달, chefInfo review 관련 수정 및 css 수정
  client/src/component/chefInfoReview.js
  client/src/component/mypageReview.js
  client/src/component/reservationPayment.js
  client/src/modal/pictureModal.js
  client/src/pages/mypage.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleMypage.js
  client/src/styled/styledModal.js
  server/controllers/mypage/arrayImg.js
Labels: Front-end, Basic

#256 [Client] / #77 / client css 수정 작업
  client/package.json
  client/public/chefLogo.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/pages/chefInfo.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleMain.js
  client/src/todaysChefIMG/chefInfoImg.jpg
Labels: Front-end, Complete, Basic

#257 [Client / Server] / #18 / reservation payment, chefInfo review, login 관련 수정
  client/src/App.js
  client/src/app/store.js
  client/src/component/chefInfoReview.js
  client/src/component/login.js
  client/src/component/reservationDate.js
  client/src/component/reservationInfo.js
  client/src/component/reservationNotice.js
  client/src/component/reservationPayment.js
  client/src/features/reservation/reservation.js
  client/src/pages/reservation.js
  client/src/pages/reservationDonePage.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleMypage.js
  client/src/styled/styleReservation.js
  server/controllers/reservation/payments.js
  server/controllers/reservation/reservation.js
  server/controllers/token/accessToken.js
  server/controllers/user/google.js
  server/controllers/user/kakao.js
  server/controllers/user/login.js
Labels: Front-end, Basic

#258 [Client / Server] / #19 / AOS Loading 상태에 따른 적용 및 구글 로그인 수정
  client/src/pages/chefInfo.js
  server/controllers/user/google.js
Labels: Front-end, Back-end, Basic, C:0.5h

#259 [Server] / #67 / console.log 불필요 한 거 지우기
  server/check.js
  server/controllers/admin/bechefIsConfirm.js
  server/controllers/chef/cuisine.js
  server/controllers/hashing/hashingPwd.js
  server/controllers/mypage/arrayImg.js
  server/controllers/mypage/checkReservation.js
  server/controllers/mypage/chefImg.js
  server/controllers/mypage/chefInfo.js
  server/controllers/mypage/userInfo.js
  server/controllers/reservation/payments.js
  server/controllers/reservation/reservation.js
  server/controllers/user/kakao.js
Labels: Back-end, Basic

#260 [Client] / #78 / styleBeChef input 수정
  client/src/styled/styleBeChef.js
Labels: Front-end, Basic

#261 [Client] / # 79 / console.log 삭제 및 modal 상태 관련 함수 수정
  client/src/App.js
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/adminpageReview.js
  client/src/component/chefInfoCourse.js
  client/src/component/chefInfoReview.js
  client/src/component/login.js
  client/src/component/mainSection3.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/reservationDate.js
  client/src/component/signup.js
  client/src/modal/choiceModal.js
  client/src/modal/deleteReservModal.js
  client/src/modal/loginErrorModal.js
  client/src/modal/loginModal.js
  client/src/modal/logoutModal.js
  client/src/modal/oneSentenceModal.js
  client/src/modal/oneSentenceSuccessModal.js
  client/src/modal/pictureModal.js
  client/src/modal/reservDeclinedModal.js
  client/src/modal/serverErrorModal.js
  client/src/modal/signupModal.js
  client/src/modal/submitCompleteModal.js
  client/src/pages/beChef.js
  client/src/pages/chefInfo.js
  client/src/pages/findChef.js
  client/src/pages/reservation.js
  client/src/pages/reservationDonePage.js
Labels: Front-end, Basic

#262 [Client] / #79 / warning message 지우기
  client/src/component/login.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/component/reservationDate.js
  client/src/component/reservationPayment.js
Labels: Basic

#263 [Client] / #80 / react-hook-form 관련 수정
  client/public/index.html
  client/src/component/reservationDate.js
  client/src/component/signup.js
Labels: Front-end, Basic

#264 [Client] / #81 / warning error 수정
  client/src/component/signup.js
  client/src/features/chef/chef.js
  client/src/modal/logoutModal.js
  client/src/pages/chefInfo.js
  client/src/pages/loginOrSignup.js
  client/src/pages/reservation.js
Labels: Front-end, Basic

#266 [Server] social login redirect 수정
  client/src/App.js
  server/controllers/user/google.js
Labels: Back-end, Basic

#268 [Client] / #83 / client mypage css 수정
  client/src/App.js
  client/src/component/mypageChefEdit.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleMypage.js
  server/controllers/user/google.js
Labels: Front-end, Back-end, Basic

#269 [Client / Server] 배포하기
  client/src/component/mypageChefEdit.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleMypage.js
  server/controllers/user/google.js
Labels: Front-end, Back-end, Basic

#270 [Client] 셰프 img cover에 맞추기
  client/src/component/chefInfoInfo.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMypage.js
Labels: Front-end, Basic

#271 [Client] / #84 / css 수정
  client/src/component/adminpageBechef.js
  client/src/component/adminpageLoading.js
  client/src/component/mypageChefEdit.js
  client/src/pages/adminpage.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleMypage.js
Labels: Front-end, Basic

#273 [Client] 셰프 img cover에 맞추기
  client/src/styled/styleChefInfo.js
Labels: Front-end, Basic

#274 [Client / Server] / web 결제 시 저장되는 정보 수정 및 date 수정
  client/src/component/adminpageBechef.js
  client/src/component/adminpageLoading.js
  client/src/component/chefInfoInfo.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageReservation.js
  client/src/pages/adminpage.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMypage.js
  server/controllers/reservation/payments.js
Labels: Front-end, Back-end, Basic

#275 [Client] axios url 관련 수정
  client/src/component/reservationPayment.js
Labels: Front-end, Basic

#276 [Client / Server] 배포 머지 관련
  client/src/component/mypageReservation.js
  client/src/component/reservationPayment.js
  server/controllers/reservation/payments.js
Labels: Basic

#277 [Client] / #86 / reservation시 인원 선택 select 변경
  client/src/component/reservationDate.js
  client/src/pages/reservation.js
Labels: Front-end

#278 [Client] dev를 main으로 머지
  client/src/component/reservationDate.js
  client/src/pages/reservation.js
Labels: Front-end

#279 [Client] / #88 / mypage chefEdit 인원 입력 관련 수정
  client/src/component/mypageChefEdit.js
Labels: Front-end, Basic

#280 [Client / Server] 최종 배포 수정 완료
  client/src/component/mypageChefEdit.js
  server/controllers/mainpage/bestChef.js
Labels: Front-end, Back-end, Complete, Basic

#281 [Client / Server] 셰프 평점 관련 수정
  client/src/component/mainSection3.js
  client/src/features/user/user.js
  client/src/pages/findChef.js
  server/controllers/mainpage/bestChef.js
Labels: Front-end, Basic
