Repository MouseGamza/Todays-Chef, pull requests merged in 2021-11, with the labels that each got.

#40 [Client] / #10 / styleMain.js : font-size 반응형으로 변경
  client/src/styled/styleMain.js
Labels: Front-end, Complete, Basic, C:1h

#41 [Client] / #11 / nav에 throttle 및 반응형 구현과 배경 고정
  client/package.json
  client/src/App.js
  client/src/component/nav.js
  client/src/styled/styleMain.js
  client/src/styled/styleNav.js
Labels: Front-end, Basic, C:3h

#42 [Client] / #11 / nav에 throttle 및 반응형 구현과 배경 고정 branch 변경
  .github/ISSUE_TEMPLATE/----client--------.md
  client/package.json
  client/src/App.css
  client/src/component/nav.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleNav.js
  client/src/todaysChefIMG/basic_profile.jpeg
Labels: Front-end

#43 [Client] / #12 / merge 오류 수정
  client/src/component/nav.js
Labels: Front-end, Basic

#44 [Client] / #13 / dev에서 merge 안된 부분 수정
  client/package.json
  client/src/component/nav.js
  client/src/styled/styleMain.js
  client/src/styled/styleNav.js
Labels: Front-end, Basic

#45 [Client] / #14 / nav 햄버거 버튼 및 animation 구현
  client/src/App.js
  client/src/component/nav.js
  client/src/styled/styleMain.js
  client/src/styled/styleNav.js
Labels: Front-end, Basic, C:3h

#46 [Client] / #15 / styleNav.js : css merge 안 된 부분 재수정
  client/src/styled/styleNav.js
Labels: Front-end, Complete, Basic, C:0.5h

#47 [Client] / #16 / main 반응형 css 수정
  client/src/component/nav.js
  client/src/styled/styleMain.js
  client/src/styled/styleNav.js
Labels: Basic, C:1h

#48 [Server] / #20 / 서버 post login 작업 및 accessToken/refreshToken 작업
  server/.env.example
  server/app.js
  server/controllers/token/accessToken.js
  server/controllers/token/refreshToken.js
  server/controllers/user/index.js
  server/controllers/user/login.js
  server/package-lock.json
  server/package.json
  server/routes/user.js
Labels: Back-end, Basic, C:2h

#49 [Client] / #17 / loginOrSignup 페이지 css animation 구현
  client/src/component/login.js
  client/src/component/nav.js
  client/src/component/signup.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styleLoginOrSignup.js
  client/src/styled/styleNav.js
  client/src/styled/styledLogin.js
  client/src/styled/styledSignup.js
  client/src/todaysChefIMG/basic_background.jpg
Labels: Front-end, Basic, C:4h

#52 [Server] / #21 / dummydata 만들어주기
  server/migrations/20211023054257-create-chef.js
  server/migrations/20211023143446-create-foreign-keys.js
  server/models/chef.js
  server/models/reservation.js
  server/seeders/20211102014301-dummyUsers.js
  server/seeders/20211102020720-dummyChefs.js
  server/seeders/20211102053107-dummyCourses.js
  server/seeders/20211102060437-dummyReservations.js
  server/seeders/20211102062052-dummyReviews.js
Labels: Back-end, Complete, Basic, C:4h

#53 [Server] / #22 / accessToken 스펠링 수정
  server/controllers/user/login.js
Labels: Back-end, Complete, Basic, C:0.5h

#57 [Client] / #18 / loginOrSignup 유효성 검사 및 반응형 작업
  client/package.json
  client/src/App.css
  client/src/component/login.js
  client/src/component/nav.js
  client/src/component/signup.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styleLoginOrSignup.js
  client/src/styled/styledLogin.js
  client/src/styled/styledSignup.js
  client/src/todaysChefIMG/small_basic_background.jpg
Labels: Front-end, Basic, C:4h

#61 [Client] / #19 / nav 로고 폰트 크기 수정 및 media query 적용
  client/package.json
  client/src/App.css
  client/src/styled/styleNav.js
Labels: Front-end, Basic, C:0.5h

#63 [Server] / #24 / 회원가입 및 로그인 서버 연결 완료
  server/.env.example
  server/controllers/hashing/hashingPwd.js
  server/controllers/user/login.js
  server/controllers/user/signup.js
Labels: Back-end, Complete, Basic, C:0.5h

#64 [Client / Server] / #06 / signup 작업중
  client/.env.example
  client/package.json
  client/src/component/login.js
  client/src/component/signup.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styleLoginOrSignup.js
  client/src/styled/styledLogin.js
  client/src/styled/styledSignup.js
  server/controllers/hashing/hashingPwd.js
  server/controllers/user/signup.js
Labels: Front-end, Back-end, Basic

#65 [Client / Server] / #07 / axios 회원가입 로그인 연결
  client/src/component/login.js
  client/src/component/signup.js
  server/controllers/user/login.js
  server/controllers/user/signup.js
Labels: Front-end, Back-end, Complete, Basic, C:2h

#66 [Client] / #20 / BeChef 페이지 제작 및 css 지정
  client/src/App.js
  client/src/component/nav.js
  client/src/pages/beAChef.js
  client/src/styled/styleBeAChef.js
  client/src/styled/styleNav.js
  client/src/todaysChefIMG/beAChefBackground.jpg
  client/src/todaysChefIMG/beAChefDesc1.jpg
  client/src/todaysChefIMG/beAChefDesc2.jpg
  client/src/todaysChefIMG/beAChefDesc3.jpg
Labels: Front-end, Basic, C:3h

#69 [Server] / #22 / sequelize dependency version upgrade
  server/package-lock.json
Labels: Back-end, Complete, Basic, C:0.5h

#70 [Client] / #21 / try catch 확인
  client/src/component/login.js
  server/controllers/user/login.js
Labels: Front-end, Basic, C:0.5h

#71 [Client] / #22 / beChef 페이지 및 nav css 수정
  client/src/App.js
  client/src/component/nav.js
  client/src/pages/beChef.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleNav.js
Labels: Front-end, Basic, C:3h

#73 [Client] / #23 / Feature/login or signup
  client/src/component/login.js
  client/src/component/nav.js
  client/src/features/user/user.js
  client/src/styled/styleNav.js
Labels: Front-end, C:1h

#74 [Client] / #24 / login modal 완성 및 홈 리다이렉트
  client/src/component/login.js
  client/src/modal/loginModal.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styledModal.js
Labels: Front-end, Basic, C:3h

#75 [Client] / #25 / login, signup modal 완성
  client/src/component/login.js
  client/src/component/signup.js
  client/src/modal/signupModal.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styledModal.js
Labels: Front-end, Complete, Basic, C:2h

#76 [Server] / #26 / logout 구현
  server/controllers/user/index.js
  server/controllers/user/logout.js
  server/routes/user.js
Labels: Back-end, Complete, Basic, C:1h

#77 [Client] / #26 / 로그아웃 모달 완성 및 axios 요청 완료
  client/src/App.js
  client/src/component/nav.js
  client/src/modal/logoutModal.js
  client/src/styled/styledModal.js
Labels: Front-end, Complete, Basic, C:1h

#78 [Client] / #27 / BeAChef 페이지 css 수정
  client/src/pages/beChef.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleNav.js
  client/src/todaysChefIMG/beChefDesc1.jpg
  client/src/todaysChefIMG/beChefDesc2.jpg
  client/src/todaysChefIMG/beChefDesc3.jpg
  client/src/todaysChefIMG/beChefDesc5.jpg
Labels: Front-end, Basic, C:4h

#82 [Client] / #28 / nav bar 구현 수정
  client/src/styled/styleNav.js
Labels: Complete, Basic, C:0.5h

#83 [Client] / #29 / signup 이중 삼항식 수정
  client/src/component/nav.js
  client/src/component/signup.js
  client/src/modal/logoutModal.js
  client/src/styled/styledModal.js
Labels: Front-end, Complete, Basic, C:0.5h

#84 [Client] / #30 / beChef resume upload 부분 css 수정
  client/src/App.css
  client/src/pages/beChef.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleLoginOrSignup.js
  client/src/todaysChefIMG/beAChefDesc1.jpg
  client/src/todaysChefIMG/beAChefDesc2.jpg
  client/src/todaysChefIMG/beAChefDesc3.jpg
Labels: Front-end, Basic, C:3h

#85 [Client] / #31 / mainpage 구조 section3까지 완성
  client/src/component/mainSection2.js
  client/src/component/mainSection3.js
  client/src/component/mainSection4.js
  client/src/pages/main.js
  client/src/styled/styleMain.js
  client/src/todaysChefIMG/mainPageBeChef.jpg
Labels: Front-end, Basic, C:3h

#87 [Client] / #32 / findChef 기본 구조 및 css 세팅
  client/src/App.css
  client/src/pages/beChef.js
  client/src/pages/findChef.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleFindChef.js
  client/src/todaysChefIMG/selectCuisineBackground.jpg
Labels: Front-end, Basic, C:3h

#90 [Client] / #34 / mainpage 반응형
  client/src/styled/styleMain.js
Labels: Front-end, Basic, C:3h

#91 [Client] / #35 / chefInfo html 태그 및 반응형 css 기본 구조 작성
  client/src/component/chefAllCourse.js
  client/src/component/chefAllInfo.js
  client/src/component/chefAllReview.js
  client/src/pages/chefInfo.js
  client/src/styled/styleChefInfo.js
Labels: Front-end, C:2h

#92 [Client] / #36 / mainPage 반응형 완성
  client/src/component/mainSection3.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMain.js
  server/seeders/20211102014301-dummyUsers.js
  server/seeders/20211102020720-dummyChefs.js
Labels: Front-end, Complete, Basic, C:2h

#93 [Client] / #37 / chefInfo html 태그 구조 작성 및 반응형 css 적용
  client/src/component/chefAllCourse.js
  client/src/component/chefAllInfo.js
  client/src/component/chefAllReview.js
  client/src/component/chefInfoCourse.js
  client/src/component/chefInfoInfo.js
  client/src/component/chefInfoReview.js
  client/src/pages/chefInfo.js
  client/src/styled/styleBeChef.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleMain.js
Labels: Front-end, C:5h

#100 [Sever] / #27 / seed 수정중
  client/src/component/mainSection4.js
  client/src/styled/styleMain.js
  server/seeders/20211102014301-dummyUsers.js
  server/seeders/20211102020720-dummyChefs.js
Labels: Back-end, Basic, C:2h

#101 [Server] / #28 / seed 수정 완료 및 chefInfo 서버 진행중
  server/app.js
  server/controllers/chef/chefId.js
  server/controllers/chef/cuisine.js
  server/controllers/chef/index.js
  server/controllers/index.js
  server/controllers/user/login.js
  server/routes/chef.js
  server/seeders/20211102020720-dummyChefs.js
  server/seeders/20211102060437-dummyReservations.js
  server/seeders/20211102062052-dummyReviews.js
Labels: Back-end, Basic, C:4h

#99 [Client] / #38 / 반응형 nav, chefInfo css 수정 및 클릭했을 때 보일 사진 모달 기본 작업
  client/src/component/chefInfoCourse.js
  client/src/component/chefInfoInfo.js
  client/src/component/chefInfoReview.js
  client/src/component/nav.js
  client/src/component/reservationDate.js
  client/src/component/reservationDone.js
  client/src/component/reservationInfo.js
  client/src/component/reservationNotice.js
  client/src/component/reservationPayment.js
  client/src/modal/pictureModal.js
  client/src/pages/chefInfo.js
  client/src/pages/findChef.js
  client/src/pages/reservation.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleNav.js
  client/src/styled/styleReservation.js
  client/src/styled/styledModal.js
Labels: Front-end, Basic, C:4h

#102 [Server] / #29 / chefInfo 상세페이지 서버 완료
  server/controllers/chef/chefId.js
Labels: Back-end, Complete, Basic, C:3h

#103 [Client] / #38 / findChef 페이지 관련 css 수정과 axios 작업
  client/src/App.js
  client/src/component/chefInfoCourse.js
  client/src/component/chefInfoInfo.js
  client/src/component/chefInfoReview.js
  client/src/features/user/user.js
  client/src/pages/chefInfo.js
  client/src/pages/findChef.js
  client/src/styled/styleChefInfo.js
  client/src/styled/styleFindChef.js
  server/controllers/chef/chefId.js
  server/controllers/chef/cuisine.js
Labels: Front-end, C:2h

#104 [Server] / #30 / social login 작업중
  client/.env.example
  client/src/component/login.js
  server/.env.example
  server/controllers/user/google.js
  server/controllers/user/index.js
  server/controllers/user/kakao.js
  server/package-lock.json
  server/package.json
  server/routes/user.js
Labels: Back-end, Basic, C:1h

#107 [Server] / #31 / confing.js 수정
  server/config/config.js
Labels: Back-end, Basic, C:0.5h

#108 [Server] / #32 / start.sh 임시수정
  scripts/start.sh
Labels: Back-end, Basic, C:0.5h

#109 [Server] / #33 / start.sh 재수정
  scripts/start.sh
Labels: Back-end, Basic, C:3h

#110 [Server] / #34 / 임시파일 생성
  server/check.js
Labels: Back-end, Basic, C:0.5h

#111 [Server] / #35 / config.js port 확인차 models config 변경
  server/models/index.js
Labels: Back-end, Basic, C:0.5h

#112 [Server] / #36 / index.js port 삭제
  server/models/index.js
Labels: Back-end, Basic, C:0.5h

#113 [Client] / #39 / app.js 리다이렉트
  client/src/App.js
  client/src/pages/reservation.js
  client/src/styled/styleReservation.js
Labels: Front-end, C:0.5h

#116 [Server] / #37 / migrate rating int -> string로 변경
  server/migrations/20211023054257-create-chef.js
  server/migrations/20211023054312-create-review.js
  server/models/chef.js
  server/models/review.js
  server/seeders/20211102020720-dummyChefs.js
  server/seeders/20211102062052-dummyReviews.js
Labels: Back-end, Complete, Basic, C:0.5h

#115 [Client] / #40 / findchef pagenation 재적용
  client/package.json
  client/src/App.js
  client/src/component/chefInfoCourse.js
  client/src/component/chefInfoInfo.js
  client/src/component/reservationDate.js
  client/src/component/reservationDone.js
  client/src/component/reservationInfo.js
  client/src/component/reservationNotice.js
  client/src/component/reservationPayment.js
  client/src/pages/findChef.js
  client/src/pages/reservation.js
  client/src/styled/styleReservation.js
  server/check.js
  server/config/config.js
Labels: Front-end

#117 [Client / server] / #08 / Merge 된 부분 확인차 전체 합치기
  server/migrations/20211023054257-create-chef.js
  server/migrations/20211023054312-create-review.js
  server/models/chef.js
  server/models/review.js
  server/seeders/20211102020720-dummyChefs.js
  server/seeders/20211102062052-dummyReviews.js
Labels: Front-end, Back-end, Basic, C:0.5h

#118 [Client / Server] dev branch -> main branch
  client/package.json
  client/src/component/chefInfoCourse.js
  client/src/component/chefInfoInfo.js
  client/src/component/reservationDate.js
  client/src/component/reservationDone.js
  client/src/component/reservationInfo.js
  client/src/component/reservationNotice.js
  client/src/component/reservationPayment.js
  client/src/pages/findChef.js
  client/src/pages/reservation.js
  client/src/styled/styleReservation.js
  server/controllers/user/login.js
Labels: Front-end, Back-end, Basic, C:0.5h

#119 [Server] / #39 / Token 으로 인한 pending 상태 의심으로 주석처리 시험
  server/controllers/user/login.js
Labels: Back-end, Basic, C:0.5h

#120 [Server] / #39 / Token 으로 인한 pending 상태 의심으로 주석처리 재시험
  server/controllers/user/login.js
Labels: Back-end, Basic, C:0.5h

#121 [Server] / #40 / accessToken 으로 인한 pending 상태 의심으로 재시험
  server/controllers/user/login.js
Labels: Back-end, Basic, C:0.5h

#122 [Server] / #41 / accessToken으로 인한 start.sh 파인 재수정
  scripts/start.sh
  server/controllers/user/login.js
Labels: Back-end, Basic, C:0.5h

#123 [Server] branch main pull -> chef review 세분화하기
  scripts/start.sh
  server/controllers/chef/chefId.js
Labels: Back-end, Complete, Basic, C:1h

#124 [Server] / #43 / chef review 갯수 startNum과 endNum의 숫자에 따라 slice 하기 구현
  server/controllers/chef/chefId.js
Labels: Back-end, Complete, Basic, C:0.5h

#125 [Client] / #41 / react date-picker 달력 관련 수정 및 예약 작성중
  client/package.json
  client/src/App.css
  client/src/component/chefInfoInfo.js
  client/src/component/chefInfoReview.js
  client/src/component/reservationDate.js
  client/src/component/reservationInfo.js
  client/src/component/reservationNotice.js
  client/src/pages/findChef.js
  client/src/pages/reservation.js
  client/src/styled/customCalander.css
  client/src/styled/styleChefInfo.js
  client/src/styled/styleReservation.js
Labels: Front-end, C:4h

#126 [ Client / Server ] / #09 / 카카오 소셜 로그인 server / client 구현 완료
  client/.env.example
  client/src/App.js
  client/src/component/signup.js
  client/src/modal/loginErrorModal.js
  client/src/pages/loginOrSignup.js
  server/controllers/user/kakao.js
  server/controllers/user/signup.js
Labels: Front-end, Back-end, Complete, Basic, C:5h

#127 [Client] / #42 / reservation 기능 구현 및 주소 검색
  client/package.json
  client/src/component/reservationDate.js
  client/src/component/reservationInfo.js
  client/src/modal/addressModal.js
  client/src/pages/reservation.js
  client/src/styled/styleReservation.js
  client/src/styled/styledModal.js
Labels: Front-end, C:5h

#130 [Client] / #43 / chefInfo, reservation, nav, signup 수정
  client/src/component/chefInfoReview.js
  client/src/component/nav.js
  client/src/component/reservationDate.js
  client/src/component/signup.js
  client/src/pages/chefInfo.js
  client/src/pages/findChef.js
  client/src/styled/styleNav.js
Labels: Front-end, C:2h

#131 [Server] / #43 / reservation 경로 구현
  server/app.js
  server/controllers/chef/chefId.js
  server/controllers/index.js
  server/controllers/reservation/findCourse.js
  server/controllers/reservation/index.js
  server/controllers/reservation/reservation.js
  server/controllers/user/kakao.js
  server/routes/reservation.js
Labels: Back-end, Basic, C:4h

#132 [Client] / #44 / reservation form 관련 수정
  client/src/component/chefInfoCourse.js
  client/src/component/reservationDate.js
  client/src/component/reservationInfo.js
  client/src/component/reservationNotice.js
  client/src/component/reservationPayment.js
  client/src/modal/addressModal.js
  client/src/pages/chefInfo.js
  client/src/pages/reservation.js
  client/src/styled/styleReservation.js
  server/controllers/chef/chefId.js
Labels: Front-end, C:5h

#134 [Server] / #44 / reservation token 만료와 만료되지 않았을 때로 구분해서 post 요청 구현
  server/controllers/reservation/reservation.js
Labels: Back-end, Complete, Basic, C:1h

#135 [Server] / #45 / 구글 로그인 구현 완료
  client/.env.example
  client/src/App.js
  client/src/component/login.js
  server/.env.example
  server/controllers/user/google.js
  server/controllers/user/kakao.js
  server/package-lock.json
  server/package.json
Labels: Back-end, Complete, Basic, C:3h

#136 [Client] / #45 / admin 기본 세팅 및 modal 관련 redux 작업
  client/src/App.js
  client/src/app/store.js
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/adminpageReview.js
  client/src/component/login.js
  client/src/component/nav.js
  client/src/component/signup.js
  client/src/features/user/modal.js
  client/src/modal/loginErrorModal.js
  client/src/modal/loginModal.js
  client/src/modal/logoutModal.js
  client/src/modal/signupModal.js
  client/src/pages/adminpage.js
  client/src/pages/loginOrSignup.js
  client/src/styled/styleAdminpage.js
Labels: Front-end, C:4h

#137 [Server] / #46 / migrate/seed 완성
  server/migrations/20211121120108-create-bechef.js
  server/migrations/20211121121326-create-foreign-keys.js
  server/models/bechef.js
  server/seeders/20211102014301-dummyUsers.js
  server/seeders/20211122013830-dummyBechef.js
Labels: Back-end, Complete, Basic, C:4h

#138 [Server] / #47 / admin review get 요청 구현 완료
  server/app.js
  server/controllers/admin/index.js
  server/controllers/admin/review.js
  server/controllers/index.js
  server/routes/admin.js
Labels: Back-end, Complete, Basic, C:2h

#139 [Server] / #48 / admin review params 추가
  server/controllers/admin/review.js
  server/routes/admin.js
Labels: Back-end, Complete, Basic, C:0.5h

#140 [Client] / #46 / admin, reservation, nav 관련 작업
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/adminpageReview.js
  client/src/component/login.js
  client/src/component/nav.js
  client/src/features/user/modal.js
  client/src/features/user/user.js
  client/src/modal/reservDeclinedModal.js
  client/src/pages/adminpage.js
  client/src/pages/loginOrSignup.js
  client/src/pages/reservation.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleFindChef.js
Labels: Front-end, C:5h

#141 [Server] / #49 / adminPage 리뷰/셰프 조회 및 삭제 구현 완료
  server/controllers/admin/chef.js
  server/controllers/admin/index.js
  server/controllers/admin/review.js
  server/routes/admin.js
Labels: Back-end, Complete, Basic, C:4h

#142 [Client] / #47 / admin review select css 수정
  client/src/styled/styleAdminpage.js
Labels: Front-end, Complete, Basic, C:0.5h

#143 [Client] / #48 / admin페이지에서 bechef, chef 컴포넌트 기본 작업
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/adminpageReview.js
  client/src/styled/styleAdminpage.js
  server/controllers/admin/chef.js
  server/controllers/admin/review.js
  server/routes/admin.js
Labels: Front-end, C:3h

#145 [Client / Server] / #10 / s3-bucket, multer 적용 및 axios 수정
  client/src/pages/beChef.js
  server/.env.example
  server/controllers/chef/index.js
  server/controllers/chef/pdfFile.js
  server/controllers/token/accessToken.js
  server/migrations/20211023054237-create-user.js
  server/migrations/20211121120108-create-bechef.js
  server/modules/multer.js
  server/package-lock.json
  server/package.json
  server/routes/chef.js
  server/seeders/20211102014301-dummyUsers.js
  server/seeders/20211122013830-dummyBechef.js
Labels: Front-end, Back-end, Complete, Basic, C:4h

#146 [Client] / #49 / admin페이지 css 수정 및 redux user 기초 상태값 수정
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/login.js
  client/src/component/nav.js
  client/src/features/user/user.js
  client/src/pages/adminpage.js
  client/src/pages/beChef.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleBeChef.js
  server/controllers/user/signup.js
  server/models/user.js
Labels: Front-end, C:2h

#147 [Client] / #50 / beChef 관련 css 및 에러메세지 작업
  client/src/pages/beChef.js
  client/src/styled/styleBeChef.js
Labels: C:2h

#148 [Server] / #50 / 날짜 계산하기 구현
  server/controllers/admin/bechef.js
  server/controllers/admin/index.js
  server/controllers/chef/pdfFile.js
  server/models/bechef.js
  server/routes/admin.js
Labels: Back-end, Basic, C:3h

#149 [Client] / #51 / reservation axios, css 작업
  client/src/component/reservationDone.js
  client/src/component/reservationPayment.js
  client/src/styled/styleReservation.js
  server/controllers/reservation/reservation.js
Labels: Front-end, C:3h

#150 [Server] / #51 / bechefs models 오류 수정 및 추가 작업
  server/controllers/chef/pdfFile.js
  server/controllers/user/google.js
  server/controllers/user/kakao.js
  server/migrations/20211121121326-create-foreign-keys.js
  server/models/bechef.js
Labels: Back-end, Basic, C:1h

#151 [Server] / #52 / adminPage 시간 filter 구현 및 구글 소셜 로그인 시 에러 발생 수정
  server/controllers/admin/bechef.js
  server/controllers/user/google.js
Labels: Back-end, Complete, Basic, C:2h

#152 [Server] / #53 / adminpage accessToken 및 refreshToken 유효성 검사 전체 추가
  server/controllers/admin/bechef.js
  server/controllers/admin/chef.js
  server/controllers/admin/review.js
  server/controllers/chef/pdfFile.js
Labels: Back-end, Basic, C:2h

#153 [Client] / #52 / reservation axios 작업 수정
  client/src/App.js
  client/src/component/adminpageBechef.js
  client/src/component/adminpageChef.js
  client/src/component/adminpageReview.js
  client/src/component/reservationPayment.js
  client/src/features/user/user.js
  client/src/pages/beChef.js
  client/src/pages/findChef.js
  client/src/styled/styleAdminpage.js
  client/src/styled/styleReservation.js
Labels: Front-end, C:4h

#154 [Server] admin page bechef 수락 및 거절 구현 / nodemailer 활용
  package-lock.json
  server/controllers/admin/bechef.js
  server/controllers/admin/bechefConfirm.js
  server/controllers/admin/bechefRefuse.js
  server/controllers/admin/index.js
  server/controllers/sendMail.js
  server/package-lock.json
  server/package.json
  server/routes/admin.js
Labels: Back-end, Basic, C:3h

#155 [Server] / #55 / admin page bechef confirm/refuse 메일 전송 구현 완료
  server/controllers/admin/bechefConfirm.js
  server/controllers/admin/bechefIsConfirm.js
  server/controllers/admin/bechefRefuse.js
  server/controllers/admin/index.js
  server/controllers/sendMail.js
  server/controllers/user/google.js
  server/routes/admin.js
Labels: Back-end, Complete, Basic, C:2h

#156 [Server] / #55 / admin bechef nickname 추가
  server/controllers/admin/bechef.js
Labels: Back-end, Complete, Basic, C:1h

#163 [Server] / #56 / mypage 예약 확인 및 취소, review table 수정
  server/app.js
  server/controllers/admin/chef.js
  server/controllers/index.js
  server/controllers/mypage/checkReservation.js
  server/controllers/mypage/index.js
  server/controllers/mypage/review.js
  server/controllers/reservation/reservation.js
  server/migrations/20211023054312-create-review.js
  server/models/review.js
  server/routes/mypage.js
  server/seeders/20211102060437-dummyReservations.js
  server/seeders/20211102062052-dummyReviews.js
Labels: Back-end, Basic, C:3h

#164 [Client] / #54 / mypage 기본 html, css 작업
  client/src/component/adminpageBechef.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/component/nav.js
  client/src/styled/styleFindChef.js
  client/src/styled/styleMypage.js
Labels: Front-end, C:3h

#169 [Server] / #57 / mypage review 기본 세팅 완료
  server/controllers/mypage/checkReview.js
  server/controllers/mypage/index.js
  server/controllers/mypage/review.js
  server/routes/mypage.js
Labels: Back-end, Basic, C:0.5h

#170 [Server] / #58 / mypage review 및 userInfo 페이지 서버 구현 완료
  server/controllers/mypage/checkReview.js
  server/controllers/mypage/index.js
  server/controllers/mypage/userInfo.js
  server/routes/mypage.js
Labels: Back-end, Complete, Basic, C:5h

#171 [Client] / #55 / mypage 기초 틀 작업 및 달력 관련 작업
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/features/reservation/reservation.js
  client/src/styled/styleMypage.js
Labels: Front-end, C:5h

#172 [Client / Server] / #11 / 사진 여러장 업로드 multer 작업
  client/src/component/mypageReview.js
  server/routes/chef.js
  server/routes/mypage.js
Labels: Front-end, Back-end, Basic, C:0.5h

#175 [Client] / #56 / mypage 반응형 구현 및 chef 관련 redux 수정
  client/src/app/store.js
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/nav.js
  client/src/features/chef/chef.js
  client/src/styled/styleMypage.js
  client/src/styled/styleNav.js
Labels: C:5h

#177 [Client] / #57 / mypage review 반응형 구현
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReservation.js
  client/src/component/mypageReview.js
  client/src/features/reservation/reservation.js
  client/src/styled/styleMypage.js
  server/controllers/mypage/checkReservation.js
Labels: Front-end, Basic, C:2h

#180 [Client] / #58 / mypage reservation axios, redux 작업중
  client/src/component/mypageReservation.js
  client/src/features/reservation/reservation.js
  client/src/features/user/modal.js
  client/src/modal/deleteReservModal.js
  client/src/pages/mypage.js
  client/src/styled/styleMypage.js
Labels: Front-end, C:3h

#181 [Client / Server] / #12 / mypage 서버 작업 완료 및 이미지 multer 구현 완료
  client/src/component/mypageChefEdit.js
  client/src/component/mypageEdit.js
  client/src/component/mypageReview.js
  server/controllers/mypage/arrayImg.js
  server/controllers/mypage/chefInfo.js
  server/controllers/mypage/image.js
  server/controllers/mypage/index.js
  server/routes/mypage.js
Labels: Front-end, Back-end, Complete, Basic, C:3h
